### PR TITLE
Add pentesting-guide to publications

### PR DESCRIPTION
**Pull request by oxr463**
Bug: https://github.com/oxr463/pentesting-guide/issues/2

### CODE REVIEW

**Comment by mhils** [comment]
Thanks! Can you please correct the publication date, adjust your position in the JSON to reflect that?

**Comment by oxr463** [comment]
Oops! That's what I get for copying and pasting the previous entry. Let me fix that.

**Comment by oxr463** [comment]
> Thanks! Can you please correct the publication date, adjust your position in the JSON to reflect that?

Please squash before merging. Thanks!

**Comment by Kriechi** [comment]
Oh wait... `"type": "guide"` is not going to show up anywhere? Was that intended?

**Comment by mhils** [comment]
Uh. Let's change it to blog post for now. We may have more guides at some point that warrant their own category.

**Comment by oxr463** [comment]
> Oh wait... `"type": "guide"` is not going to show up anywhere? Was that intended?

I assumed the categories would auto-populate.

**Pull request merged**
